- hosts: localhost
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - full
  become_method: sudo
  tasks: 
  #asdf
  - name: Clone asdf repo
    shell: git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.14.0
    tags: asdf
  #python
  - name: Add python plugin
    shell: asdf plugin-add python
    tags: 
    - asdf
    - python
  - name: Install latest python release
    shell: asdf install python latest
    tags: 
    - asdf
    - python
  - name: Set latest python to global
    shell: asdf global python latest
    tags: 
    - asdf
    - python
  #ruby
  - name: Add ruby plugin
    shell: asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
    tags: 
    - asdf
    - ruby
  - name: Install latest ruby release
    shell: asdf install ruby latest
    tags: 
    - asdf
    - ruby
  - name: Set latest ruby to global
    shell: asdf global ruby latest
    tags: 
    - asdf
    - ruby
  #nodejs
  - name: Add nodejs plugin
    shell: asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    tags: 
    - asdf
    - nodejs
  - name: Install latest nodejs release
    shell: asdf install nodejs latest
    tags: 
    - asdf
    - nodejs
  - name: Set latest nodejs to global
    shell: asdf global nodejs latest
    tags: 
    - asdf
    - nodejs
  #rust
  - name: Add rust plugin
    shell: asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
    tags: 
    - asdf
    - rust
  - name: Install latest rust release
    shell: asdf install rust latest
    tags: 
    - asdf
    - rust
  - name: Set latest rust to global
    shell: asdf global rust latest
    tags: 
    - asdf
    - rust
  - name: Install rust CLI tool tealdeer
    shell: cargo install tealdeer
    tags: 
    - asdf
    - rust_tools
  #golang
  - name: Add golang plugin
    shell: asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
    tags: 
    - asdf
    - golang
  - name: Install latest golang release
    shell: asdf install golang latest
    tags: 
    - asdf
    - golang
  - name: Set latest golang to global
    shell: asdf global golang latest
    tags: 
    - asdf
    - golang
  #postgreSQL
  - name: Add postgres plugin
    shell: asdf plugin add postgres
    tags: 
    - asdf
    - postgres
  - name: Install latest postgres release
    shell: asdf install postgres latest
    tags: 
    - asdf
    - postgres
  - name: Set latest postgres to global
    shell: asdf global postgres latest
    tags: 
    - asdf
    - postgres
  #MySQL
  - name: Add mysql plugin
    shell: asdf plugin add mysql
    tags: 
    - asdf
    - mysql
  - name: Install latest mysql release
    shell: asdf install mysql latest
    tags: 
    - asdf
    - mysql
  - name: Set latest mysql to global
    shell: asdf global mysql latest
    tags: 
    - asdf
    - mysql
