- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - full
  become_method: sudo
  tasks:
  - include: tasks/host_key_script.yml 
  - include: tasks/ssh.yml
  - include: tasks/core.yml 
  - include: tasks/alacritty.yml
  - include: tasks/discord.yml
  - include: tasks/docker.yml
  - include: tasks/nvim.yml
  - include: tasks/f_roll.yml
  - include: tasks/zsh.yml
  - include: tasks/i3wm.yml
  - include: tasks/dotfiles.yml
  - include: tasks/reboot.yml
