#alacritty
- name: Add alacritty repository to apt
  become: true
  shell: sudo add-apt-repository ppa:aslatter/ppa
  tags: alacritty
- name: install alacritty
  become: true
  shell: sudo apt install alacritty
  tags: alacritty
#Nerd Font
- name: Download Meslo Regular
  shell: curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf -o ~/.local/share/fonts/MesloLGS\ NF\ Regular.ttf
  tags: font
- name: Download Meslo Bold
  shell: curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf -o ~/.local/share/fonts/MesloLGS\ NF\ Bold.ttf
  tags: font
- name: Download Meslo Italic
  shell: curl -L curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf -o ~/.local/share/fonts/MesloLGS\ NF\ Italic.ttf
  tags: font
- name: Download Meslo Bold Italic
  shell: curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -o ~/.local/share/fonts/MesloLGS\ NF\ Bold\ Italic.ttf
  tags: font