- name: Download all Core apt packages
  become: true
  apt:
    name: [build-essential, curl, wget, libpq-dev, libssl-dev, fontconfig, neovim, fzf, lsof, stow, imagemagick, libmagickwand-dev, ncurses-term, exuberant-ctags, make, zlib1g-dev, 
libbz2-dev, libreadline-dev, libsqlite3-dev, llvm, libncursesw5-dev, xz-utils, tk-dev, libxml2-dev, libxmlsec1-dev, libffi-dev, libffi-dev, liblzma-dev,
autoconf, bison, rustc, libyaml-dev, libyaml-dev, libreadline6-dev, libgmp-dev, libncurses5-dev, libgdbm6, libgdbm-dev, libdb-dev, uuid-dev, ubuntu-restricted-extras,]

- name: Download Nvidia Drivers
  become: true
  apt:
    name: [nvidia-driver-515, nvidia-dkms-515]

