- name: Download Discord Package
  become: true
  shell: curl -L -o discord.deb https://discord.com/api/download?platform=linux&format=deb
  tags: discord

- name: Install Discord
  become: true
  shell: apt install ./discord.deb -y && rm -f ./discord.deb
