- name: Remove Conflicting Packages
  become: true
  shell: for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
  tags: docker
- name: Execute Docker Script
  become: true
  shell: bash $HOME/ansible/scripts/docker
  tags: docker
- name: Install Latest Docker Version
  become: true
  shell: apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  tags: docker
