- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:PedroDrago/.dotfiles.git'
    dest: "$HOME/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && bash stow_script.sh
  tags: dotfiles