- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:PedroDrago/.dotfiles.git'
    dest: "$HOME/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
  tags: dotfiles
- name: Setup dotfiles
  shell: cd $HOME/.dotfiles/desktop && bash stow_script.sh
  tags: dotfiles
