- name: Download firefox tar
  become: true
  shell: curl -L https://download.mozilla.org/\?product\=firefox-latest-ssl\&os\=linux64\&lang\=pt-BR -o firefox.tar
  tags: firefox

- name: untar firefox tar
  become: true
  shell: tar xjf firefox.tar
  tags: firefox

- name: move uncompressed firefox to /opt
  become: true
  shell: mv firefox /opt
  tags: firefox

- name: create symlink to firefox executable
  become: true
  shell: ln -s /opt/firefox/firefox /usr/local/bin/firefox
  tags: firefox
