- name: Install i3wm
  become: true
  apt: name=i3
  tags: i3wm
- name: Create i3 config directory
  shell: mkdir $HOME/.config/i3
  tags: i3wm
- name: Instal i3lock
  become: true
  shell: apt install i3lock xautolock 
  tags: i3wm