- name: Download appimage
  become: true
  shell: curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && chmod +x nvim.appimage
  tags: nvim
- name: Make nvim global
  become: true
  shell: mv nvim.appimage /usr/bin/nvim
