- name: Download appimage
  become: true
  shell: curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && chmod u+x nvim.appimage && mv nvim.appimage /usr/bin/nvim
  tags: nvim
# - name: Fix error
#   become: true
#   shell: ./nvim.appimage --appimage-extract && ./squashfs-root/AppRun --version
# - name: Make nvim global
#   become: true
#   shell: sudo mv squashfs-root && sudo ln -s /squashfs-root/AppRun /usr/bin/nvim && nvim

