- name: Download Obsidian Snap
  shell: curl -L https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.16/obsidian_1.4.16_amd64.deb -o obsidian.deb
  tags: obsidian
- name: Install Obsidian
  become: true
  shell: apt install ./obsidian.deb
  tags: obsidian
- name: Delete snapfile
  shell: rm -f obsidian.deb
  tags: obsidian
