- name: Create file repository configuration
  become: true
  shell: sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  tags: postgresql
- name: Import repository key
  become: true
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  tags: postgresql
- name: Update apt
  become: true
  shell: apt-get update
  tags: postgresql
- name: Download postgresql
  become: true
  shell: apt-get -y postgresql
  tags: postgresql

- name: Install key
  become: true
  shell: curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
  tags: pgadmin
- name: Create repository file
  become: true
  shell: sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
  tags: pgadmin
- name: Download pgadmin
  become: true
  shell: sudo apt install pgadmin4
  tags: pgadmin

  #sudo /usr/pgadmin4/bin/setup-web.sh -> this command is necessary to run by myself to configure pgadmin user
