#zsh
- name: Install zsh
  become: true
  apt: name=zsh
  tags: zsh
- name: Change default shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: zsh
#oh-my-zsh + plugins
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags: zsh
- name: Clone powerlevel10k
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  tags: zsh
- name: Clone autosuggestion plugin
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/plugins/zsh-autosuggestions
  tags: zsh
- name: Clone syntax highlight plugin
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/plugins/zsh-syntax-highlighting
  tags: zsh
